/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface AgriDataRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizeRelayer"
      | "authorizedRelayers"
      | "batchRoots"
      | "batchTimestamps"
      | "getBatchRoot"
      | "getBatchTimestamp"
      | "owner"
      | "registerDataBatch"
      | "revokeRelayer"
      | "transferOwnership"
      | "verifyDataInclusion"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchRegistered"
      | "RelayerAuthorized"
      | "RelayerRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizeRelayer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedRelayers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchRoots",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchTimestamps",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBatchRoot",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBatchTimestamp",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerDataBatch",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRelayer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyDataInclusion",
    values: [BytesLike, BytesLike, BytesLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizeRelayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedRelayers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "batchRoots", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchTimestamps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBatchRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBatchTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerDataBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeRelayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyDataInclusion",
    data: BytesLike
  ): Result;
}

export namespace BatchRegisteredEvent {
  export type InputTuple = [
    batchId: BytesLike,
    merkleRoot: BytesLike,
    timestamp: BigNumberish,
    relayer: AddressLike
  ];
  export type OutputTuple = [
    batchId: string,
    merkleRoot: string,
    timestamp: bigint,
    relayer: string
  ];
  export interface OutputObject {
    batchId: string;
    merkleRoot: string;
    timestamp: bigint;
    relayer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RelayerAuthorizedEvent {
  export type InputTuple = [relayer: AddressLike];
  export type OutputTuple = [relayer: string];
  export interface OutputObject {
    relayer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RelayerRevokedEvent {
  export type InputTuple = [relayer: AddressLike];
  export type OutputTuple = [relayer: string];
  export interface OutputObject {
    relayer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgriDataRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AgriDataRegistry;
  waitForDeployment(): Promise<this>;

  interface: AgriDataRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeRelayer: TypedContractMethod<
    [relayer: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedRelayers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  batchRoots: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  batchTimestamps: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  getBatchRoot: TypedContractMethod<[batchId: BytesLike], [string], "view">;

  getBatchTimestamp: TypedContractMethod<
    [batchId: BytesLike],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerDataBatch: TypedContractMethod<
    [batchId: BytesLike, merkleRoot: BytesLike],
    [void],
    "nonpayable"
  >;

  revokeRelayer: TypedContractMethod<
    [relayer: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyDataInclusion: TypedContractMethod<
    [batchId: BytesLike, leaf: BytesLike, proof: BytesLike[]],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeRelayer"
  ): TypedContractMethod<[relayer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedRelayers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "batchRoots"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "batchTimestamps"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBatchRoot"
  ): TypedContractMethod<[batchId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getBatchTimestamp"
  ): TypedContractMethod<[batchId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerDataBatch"
  ): TypedContractMethod<
    [batchId: BytesLike, merkleRoot: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRelayer"
  ): TypedContractMethod<[relayer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyDataInclusion"
  ): TypedContractMethod<
    [batchId: BytesLike, leaf: BytesLike, proof: BytesLike[]],
    [boolean],
    "view"
  >;

  getEvent(
    key: "BatchRegistered"
  ): TypedContractEvent<
    BatchRegisteredEvent.InputTuple,
    BatchRegisteredEvent.OutputTuple,
    BatchRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "RelayerAuthorized"
  ): TypedContractEvent<
    RelayerAuthorizedEvent.InputTuple,
    RelayerAuthorizedEvent.OutputTuple,
    RelayerAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "RelayerRevoked"
  ): TypedContractEvent<
    RelayerRevokedEvent.InputTuple,
    RelayerRevokedEvent.OutputTuple,
    RelayerRevokedEvent.OutputObject
  >;

  filters: {
    "BatchRegistered(bytes32,bytes32,uint256,address)": TypedContractEvent<
      BatchRegisteredEvent.InputTuple,
      BatchRegisteredEvent.OutputTuple,
      BatchRegisteredEvent.OutputObject
    >;
    BatchRegistered: TypedContractEvent<
      BatchRegisteredEvent.InputTuple,
      BatchRegisteredEvent.OutputTuple,
      BatchRegisteredEvent.OutputObject
    >;

    "RelayerAuthorized(address)": TypedContractEvent<
      RelayerAuthorizedEvent.InputTuple,
      RelayerAuthorizedEvent.OutputTuple,
      RelayerAuthorizedEvent.OutputObject
    >;
    RelayerAuthorized: TypedContractEvent<
      RelayerAuthorizedEvent.InputTuple,
      RelayerAuthorizedEvent.OutputTuple,
      RelayerAuthorizedEvent.OutputObject
    >;

    "RelayerRevoked(address)": TypedContractEvent<
      RelayerRevokedEvent.InputTuple,
      RelayerRevokedEvent.OutputTuple,
      RelayerRevokedEvent.OutputObject
    >;
    RelayerRevoked: TypedContractEvent<
      RelayerRevokedEvent.InputTuple,
      RelayerRevokedEvent.OutputTuple,
      RelayerRevokedEvent.OutputObject
    >;
  };
}
